language: rust
services: docker
sudo: required

matrix:
  include:
    - env: TARGET=i686-unknown-linux-gnu
      rust: stable
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: stable
    - rust: 1.22.0
      script: test --verbose --all
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=powerpc-unknown-linux-gnu
      rust: stable
    - env: TARGET=powerpc64-unknown-linux-gnu
      rust: stable
    # tests if crates truly can be built without std
    - env: TARGET=thumbv7em-none-eabi
      rust: nightly
      script: ./build_nostd.sh
      install:
        - cargo install xargo --force
        - rustup target install armv7-unknown-linux-gnueabihf
        - rustup component add rust-src

script:
  - cross test --verbose --all --release --target $TARGET

cache: cargo
install:
  - cargo install xargo --force
  - rustup target install armv7-unknown-linux-gnueabihf
  - rustup component add rust-src