[workspace]
resolver = "2"
members = [
    "ascon-hash",
    "belt-hash",
    "blake2",
    "fsb",
    "gost94",
    "groestl",
    "jh",
    "k12",
    "md2",
    "md4",
    "md5",
    "ripemd",
    "sha1",
    "sha1-checked",
    "sha2",
    "sha3",
    "shabal",
    "skein",
    "sm3",
    "streebog",
    "tiger",
    "whirlpool",
]

[profile.dev]
opt-level = 2
