[package]
name = "groestl"
version = "0.7.0"
authors = ["RustCrypto Developers"]
license = "MIT/Apache-2.0"
description = "Gr√∏stl hash function"
documentation = "https://docs.rs/groestl"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "groestl", "grostl", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
digest = "0.7"
byte-tools = "0.2"
block-buffer = "=0.2.0-tmp"

[dev-dependencies]
digest = { version = "*", features = ["dev"] }

[badges]
travis-ci = { repository = "RustCrypto/hashes" }
