[package]
name = "streebog"
version = "0.6.0"
authors = ["The Rust-Crypto Project Developers"]
license = "MIT/Apache-2.0"
description = "Streebog (GOST R 34.11-2012) hash function"
documentation = "https://docs.rs/streebog"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "streebog", "gost", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
digest = "0.7"
byte-tools = "0.2"
block-buffer = "0.3"

[dev-dependencies]
crypto-tests = "0.6"

[badges]
travis-ci = { repository = "RustCrypto/hashes" }
