[package]
name = "streebog"
version = "0.8.0"
description = "Streebog (GOST R 34.11-2012) hash function"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"
documentation = "https://docs.rs/streebog"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "streebog", "gost", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
digest = "= 0.9.0-pre"
block-buffer = "0.7"
byte-tools = "0.3"
opaque-debug = "0.2"

[dev-dependencies]
digest = { version = "= 0.9.0-pre", features = ["dev"] }
hex-literal = "0.1"

[features]
default = ["std"]
std = ["digest/std"]
