[package]
name = "blake2"
version = "0.6.0"
authors = ["The Rust-Crypto Project Developers"]
license = "MIT/Apache-2.0"
description = "BLAKE2 hash functions"
documentation = "https://docs.rs/blake2"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "blake2", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
digest = "0.6"
generic-array = "0.8"
byte-tools = "0.2"
crypto-mac = "0.4"

[dev-dependencies]
crypto-tests = "0.5"

[features]
simd = []
simd_opt = ["simd"]
simd_asm = ["simd_opt"]

[badges]
travis-ci = { repository = "RustCrypto/hashes" }
