[package]
name = "blake2"
version = "0.7.1"
authors = ["RustCrypto Developers"]
license = "MIT/Apache-2.0"
description = "BLAKE2 hash functions"
documentation = "https://docs.rs/blake2"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "blake2", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
digest = "0.7"
byte-tools = "0.2"
crypto-mac = "0.5"

[dev-dependencies]
digest = { version = "^0.7.1", features = ["dev"] }
crypto-mac = { version = "^0.5.1", features = ["dev"] }

[features]
simd = []
simd_opt = ["simd"]
simd_asm = ["simd_opt"]

[badges]
travis-ci = { repository = "RustCrypto/hashes" }
