[package]
name = "blake2"
version = "0.9.2"
description = "BLAKE2 hash functions"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"
documentation = "https://docs.rs/blake2"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "blake2", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
arrayref = "0.3"
arrayvec = { version = "0.5", default-features = false }
subtle = ">=2, <2.5"
#digest = "0.9"
#crypto-mac = "0.8"
#opaque-debug = "0.3"

[dev-dependencies]
hex = "0.4"
lazy_static = "1.3.0"
rand = "0.7.0"
rand_chacha = "0.2.0"
serde = { version = "1.0.91", features = ["derive"] }
serde_json = "1.0.39"
#digest = { version = "0.9", features = ["dev"] }
#crypto-mac = { version = "0.8", features = ["dev"] }
#hex-literal = "0.2"

[features]
default = ["blake2b", "blake2s"]
blake2b = []
blake2s = []
# This crate does a lot of #[inline(always)]. For BLAKE2b on ARM Cortex-M0 (and
# presumably other tiny chips), some of that inlining actually hurts
# performance. This feature disables some inlining, improving the performance
# of the portable implementation in that specific case.
uninline_portable = []
