[package]
name = "ripemd160"
version = "0.6.0"
authors = ["The Rust-Crypto Project Developers"]
license = "MIT/Apache-2.0"
description = "RIPEMD-160 hash function"
documentation = "https://docs.rs/ripemd160"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "ripemd160", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
digest = "0.6"
generic-array = "0.8"
byte-tools = "0.2"
block-buffer = "0.2"

[dev-dependencies]
crypto-tests = "0.5"

[badges]
travis-ci = { repository = "RustCrypto/hashes" }
