[package]
name = "ripemd160"
version = "0.2.0"
authors = ["The Rust-Crypto Project Developers"]
license = "MIT/Apache-2.0"
description = "RIPEMD-160 hash function"
documentation = "https://docs.rs/ripemd160"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "ripemd160", "hash", "digest"]

[dependencies]
byte-tools = "0.1"
digest = "0.2"
digest-buffer = "0.1"
generic-array = "0.5"

[dev-dependencies]
crypto-tests = "0.1"
