[package]
name = "md2"
version = "0.10.0" # Also update html_root_url in lib.rs when bumping this
license = "MIT OR Apache-2.0"
authors = ["RustCrypto Developers"]
description = "MD2 hash function"
readme = "README.md"
edition = "2018"
documentation = "https://docs.rs/md2"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "md2", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
digest = "0.10"

[dev-dependencies]
digest = { version = "0.10", features = ["dev"] }
hex-literal = "0.2"

[features]
default = ["std"]
std = ["digest/std"]
