[package]
name = "gost94"
version = "0.2.1"
authors = ["The Rust-Crypto Project Developers"]
license = "MIT/Apache-2.0"
description = "GOST R 34.11-94 hash function"
documentation = "https://docs.rs/gost94"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "gost94", "gost", "hash", "digest"]
categories = ["cryptography"]

[dependencies]
digest-buffer = "0.2"
byte-tools = "0.1"
generic-array = "0.6"
digest = "0.4"

[dev-dependencies]
crypto-tests = "0.3"

[badges]
travis-ci = { repository = "RustCrypto/hashes" }
